spring.application.name=spring-webflux-crud

spring.r2dbc.url=r2dbc:h2:mem:///testdb
spring.r2dbc.username=sa
spring.r2dbc.password=

# Turn on useful debug logs for WebFlux and R2DBC
logging.level.org.springframework.r2dbc=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.codec=DEBUG
logging.level.reactor.netty.http.server=DEBUG
